CREATE EXTERNAL TABLE `exchange_rates`(
  `index` bigint COMMENT '', 
  `calendar_date` date COMMENT '', 
  `eur` double COMMENT '', 
  `gbp` double COMMENT '', 
  `inr` double COMMENT '', 
  `aud` double COMMENT '', 
  `cad` double COMMENT '', 
  `sgd` double COMMENT '', 
  `chf` double COMMENT '', 
  `myr` double COMMENT '', 
  `jpy` double COMMENT '', 
  `cny` double COMMENT '', 
  `ars` double COMMENT '', 
  `bhd` double COMMENT '', 
  `bwp` double COMMENT '', 
  `brl` double COMMENT '', 
  `bnd` double COMMENT '', 
  `bgn` double COMMENT '', 
  `clp` double COMMENT '', 
  `cop` double COMMENT '', 
  `hrk` double COMMENT '', 
  `czk` double COMMENT '', 
  `dkk` double COMMENT '', 
  `hkd` double COMMENT '', 
  `huf` double COMMENT '', 
  `isk` double COMMENT '', 
  `idr` double COMMENT '', 
  `irr` double COMMENT '', 
  `ils` double COMMENT '', 
  `kzt` double COMMENT '', 
  `krw` double COMMENT '', 
  `kwd` double COMMENT '', 
  `lyd` double COMMENT '', 
  `mur` double COMMENT '', 
  `mxn` double COMMENT '', 
  `npr` double COMMENT '', 
  `nzd` double COMMENT '', 
  `nok` double COMMENT '', 
  `omr` double COMMENT '', 
  `pkr` double COMMENT '', 
  `php` double COMMENT '', 
  `pln` double COMMENT '', 
  `qar` double COMMENT '', 
  `ron` double COMMENT '', 
  `rub` double COMMENT '', 
  `sar` double COMMENT '', 
  `zar` double COMMENT '', 
  `lkr` double COMMENT '', 
  `sek` double COMMENT '', 
  `twd` double COMMENT '', 
  `thb` double COMMENT '', 
  `ttd` double COMMENT '', 
  `try` double COMMENT '', 
  `aed` double COMMENT '')
ROW FORMAT DELIMITED 
  FIELDS TERMINATED BY ',' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://trabalho-ifsp-campinas-d2tec-2022-2/datasets/exchange_rates/'
TBLPROPERTIES (
  'CrawlerSchemaDeserializerVersion'='1.0', 
  'CrawlerSchemaSerializerVersion'='1.0', 
  'UPDATED_BY_CRAWLER'='d2tec-crawler', 
  'areColumnsQuoted'='false', 
  'averageRecordSize'='366', 
  'classification'='csv', 
  'columnsOrdered'='true', 
  'compressionType'='none', 
  'delimiter'=',', 
  'objectCount'='1', 
  'recordCount'='5324', 
  'sizeKey'='1948828', 
  'skip.header.line.count'='1', 
  'typeOfData'='file')